CLIENTS:
  - QUEUE_NAME: "test-123"
    SERVER: "http://127.0.0.1:18040"
    CONNECTIONS: 2
    AUTH: ["lms", "password"]
    HANDLERS:
      - HANDLER: "xqueue_watcher.jailedgrader.JailedGrader"
        CODEJAIL:
          name: "7qbwx"
          bin_path: "/path/to/venv/bin/python"
          lang: python2
          user: "user2"
        KWARGS:
          grader_root: "../data/MITx-7.QBWx/graders/"
  - QUEUE_NAME: "test-456"
    SERVER: "http://127.0.0.1:18040"
    CONNECTIONS: 2
    AUTH: ["lms", "password"]
    HANDLERS:
      - HANDLER: "xqueue_watcher.jailedgrader.JailedGrader"
        CODEJAIL:
          name: "MITx-6.00x"
          bin_path: "/path/to/venv/bin/python"
          lang: python3
          user: "user1"
        KWARGS:
            grader_root: "../data/MITx-6.00x/graders/python3graders/"

LOGGING:
    loggers:
      "":
        handlers: ["console"]
        level: "DEBUG"
      requests:
        level: "ERROR"
        handlers: ["console"]
    version: 1
    handlers:
      console:
        class: "logging.StreamHandler"
        level: "DEBUG"
        formatter: "standard"
    formatters:
      raw:
        format: "%(message)s"
      standard:
        format: "%(asctime)s %(levelname)s %(process)d [%(name)s] %(filename)s:%(lineno)d - %(message)s"

# these are the default settings
MANAGER:
  HTTP_BASIC_AUTH: null
  POLL_TIME: 10
  REQUESTS_TIMEOUT: 1
  POLL_INTERVAL: 1
  IDLE_POLL_INTERVAL: 60
  LOGIN_POLL_INTERVAL: 5
  FOLLOW_CLIENT_REDIRECTS: False
